import { BAR_CLASS, CUSTOM_PREFIX_RE, OBSIDIAN_RE, PROCESSED_ATTR } from "../shared/constants";
import { copyText, openObsidian } from "./chatgptUi";

const globalFingerprints = new Set<string>();
const fingerprint = (parts: unknown[]) => parts.map(part => String(part || "")).join("\u241F");
const getCodeText = (pre: Element) => { const clone = pre.cloneNode(true) as HTMLElement; clone.querySelectorAll(`.${BAR_CLASS}, .obsidian-chatgpt-bridge-inline-bar, .obsidian-chatgpt-bridge-button`).forEach(node => node.remove()); return (clone.textContent || "").trim(); };
const cleanUri = (raw: string) => { const textarea = document.createElement("textarea"); textarea.innerHTML = String(raw || "").trim(); let uri = textarea.value; while (/[.,;\]]$/.test(uri)) uri = uri.slice(0, -1); return uri; };
const getTopLevelPres = (root: ParentNode = document) => Array.from(root.querySelectorAll("pre")).filter(pre => !pre.parentElement?.closest("pre"));
const findMessageRoot = (el: Element) => el.closest("[data-message-author-role], article, main") || document.body;
const findCodeBlockContainer = (pre: Element) => { const root = findMessageRoot(pre); let container: Element = pre, el: Element = pre; while (el.parentElement && el.parentElement !== root && el.parentElement !== document.body) { const parent = el.parentElement; const looksCard = parent.querySelectorAll("pre").length === 1 && ((parent.querySelector("button, [role='button']")) || parent.scrollWidth > parent.clientWidth + 8 || /overflow|scroll|rounded|contain|code/i.test(String(parent.className || ""))); if (!looksCard) break; container = el = parent; } return container; };
const hasExistingBarAnywhere = (fp: string) => !!document.querySelector(`.${BAR_CLASS}[data-obsidian-fingerprint="${CSS.escape(fp)}"]`) || globalFingerprints.has(fp);
const removeDuplicateBars = () => { const seen = new Set<string>(); Array.from(document.querySelectorAll<HTMLElement>(`.${BAR_CLASS}[data-obsidian-fingerprint]`)).forEach(bar => { const fp = bar.dataset.obsidianFingerprint; if (!fp) return; if (seen.has(fp)) bar.remove(); else seen.add(fp); }); };
const parseTarget = (target: string) => { const slash = target.indexOf("/"); return slash <= 0 || slash === target.length - 1 ? null : { vault: target.slice(0, slash).trim(), filepath: target.slice(slash + 1).trim() }; };
const buildAdvancedUri = (vault: string, filepath: string, mode: string) => `obsidian://adv-uri?vault=${encodeURIComponent(vault)}&filepath=${encodeURIComponent(filepath)}&clipboard=true&mode=${encodeURIComponent(mode)}`;
const uriUsesClipboard = (uri: string) => { try { return new URL(uri).searchParams.get("clipboard") === "true"; } catch { return /[?&]clipboard=true(?:&|$)/.test(uri); } };
const fetchObsidianFile = (filepath: string) => new Promise<{ ok: boolean }>(resolve => chrome.runtime.sendMessage({ type: "FETCH_OBSIDIAN_FILE", filepath }, response => resolve(response || { ok: false })));
const resolveWriteMode = (action: string, fileExists: boolean) => !fileExists ? "overwrite" : action === "append" || action === "prepend" ? action : "overwrite";
const labelForAction = (action: string) => ({ append: "Append to Obsidian", prepend: "Prepend to Obsidian", overwrite: "Overwrite in Obsidian", create: "Create in Obsidian", update: "Update Obsidian" }[action] || "Update Obsidian");
const makeButton = (uri: string, label: string, copySourceEl?: Element | null) => { const button = document.createElement("button"); button.type = "button"; button.className = "obsidian-chatgpt-bridge-button"; button.textContent = label; button.addEventListener("click", async event => { event.preventDefault(); event.stopPropagation(); const payload = copySourceEl && uriUsesClipboard(uri) ? getCodeText(copySourceEl) : null; if (payload && !await copyText(payload)) return button.textContent = "Clipboard blocked"; openObsidian(uri); }); return button; };
const findPreviousCopyBlock = (fromEl: Element) => Array.from(findMessageRoot(fromEl).querySelectorAll("pre")).find(pre => pre !== fromEl && !pre.contains(fromEl) && pre.getBoundingClientRect().bottom <= fromEl.getBoundingClientRect().top + 4 && !OBSIDIAN_RE.test(pre.textContent || "") && getCodeText(pre));
const parseCustomObsidianBlock = (pre: Element) => { const text = getCodeText(pre); if (!text) return null; const lines = text.split(/\r?\n/); const first = (lines[0] || "").trim(); const direct = first.match(CUSTOM_PREFIX_RE); if (direct) { const parsed = parseTarget(direct[2]); return parsed ? { action: direct[1].toLowerCase(), vault: parsed.vault, filepath: parsed.filepath, content: lines.slice(1).join("\n").trim() } : null; } const code = pre.querySelector("code"); const rawValues = [code?.getAttribute("class") || "", code?.getAttribute("data-language") || "", code?.getAttribute("data-lang") || "", pre.getAttribute("data-language") || "", pre.getAttribute("data-lang") || "", ...(code ? Array.from(code.classList) : [])]; const marker = rawValues.map(value => String(value || "").replace(/^language-/, "").trim().match(CUSTOM_PREFIX_RE)).find(Boolean); if (!marker) return null; const parsed = parseTarget(marker[2]); return parsed ? { action: marker[1].toLowerCase(), vault: parsed.vault, filepath: parsed.filepath, content: text.trim() } : null; };
const insertBarAfterCodeBlock = (pre: Element, bar: HTMLElement) => { const container = findCodeBlockContainer(pre); let next = container.nextElementSibling; while (next?.classList?.contains(BAR_CLASS)) { const remove = next; next = next.nextElementSibling; remove.remove(); } container.insertAdjacentElement("afterend", bar); };

export function processCustomObsidianBlocks(root: ParentNode = document) {
  getTopLevelPres(root).forEach(node => { const custom = parseCustomObsidianBlock(node); if (!custom) return; const fp = fingerprint(["custom", custom.action, custom.vault, custom.filepath, custom.content]); if (hasExistingBarAnywhere(fp)) return node.setAttribute(PROCESSED_ATTR, "custom"); node.setAttribute(PROCESSED_ATTR, "custom"); globalFingerprints.add(fp); const bar = document.createElement("div"); bar.className = BAR_CLASS; bar.dataset.obsidianFingerprint = fp; const button = document.createElement("button"); button.type = "button"; button.className = "obsidian-chatgpt-bridge-button"; button.textContent = labelForAction(custom.action); button.addEventListener("click", async event => { event.preventDefault(); event.stopPropagation(); if (!await copyText(custom.content)) return; const result = await fetchObsidianFile(custom.filepath); openObsidian(buildAdvancedUri(custom.vault, custom.filepath, resolveWriteMode(custom.action, result.ok))); }); bar.append(button, Object.assign(document.createElement("span"), { className: "obsidian-chatgpt-bridge-meta", textContent: `${custom.vault}/${custom.filepath} · ${custom.action}` })); insertBarAfterCodeBlock(node, bar); });
}

export function processAnchors(root: ParentNode = document) { root.querySelectorAll<HTMLAnchorElement>('a[href^="obsidian://"]').forEach(anchor => { if (anchor.getAttribute(PROCESSED_ATTR)) return; anchor.setAttribute(PROCESSED_ATTR, "anchor"); anchor.addEventListener("click", event => { event.preventDefault(); event.stopPropagation(); openObsidian(anchor.href); }, true); anchor.classList.add("obsidian-chatgpt-bridge-link"); }); }
export function processCodeBlocks(root: ParentNode = document) { getTopLevelPres(root).forEach(node => { if (node.getAttribute(PROCESSED_ATTR)) return; const unique = [...new Set([...(node.textContent || "").matchAll(OBSIDIAN_RE)].map(match => cleanUri(match[0])))].filter(uri => uri.startsWith("obsidian://")); if (!unique.length) return; node.setAttribute(PROCESSED_ATTR, "code"); const fp = fingerprint(["uri", unique.join("|")]); if (hasExistingBarAnywhere(fp)) return; globalFingerprints.add(fp); const bar = document.createElement("div"); bar.className = BAR_CLASS; bar.dataset.obsidianFingerprint = fp; const copyBlock = findPreviousCopyBlock(node); unique.slice(0, 5).forEach((uri, index) => bar.appendChild(makeButton(uri, unique.length === 1 ? "Open in Obsidian" : `Open URI ${index + 1}`, copyBlock))); insertBarAfterCodeBlock(node, bar); }); }
export function processPlainText(root: ParentNode = document) { root.querySelectorAll<HTMLElement>("p, li").forEach(el => { if (el.getAttribute(PROCESSED_ATTR) || el.closest("pre, code")) return; const unique = [...new Set([...(el.textContent || "").matchAll(OBSIDIAN_RE)].map(match => cleanUri(match[0])))].filter(uri => uri.startsWith("obsidian://")); if (!unique.length) return; el.setAttribute(PROCESSED_ATTR, "plain"); const bar = document.createElement("span"); bar.className = "obsidian-chatgpt-bridge-inline-bar"; unique.slice(0, 3).forEach((uri, index) => bar.appendChild(makeButton(uri, unique.length === 1 ? "Open in Obsidian" : `Open URI ${index + 1}`))); el.append(document.createTextNode(" "), bar); }); }
export { removeDuplicateBars };
